# Generated by Django 4.0.3 on 2023-09-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_vip',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
